on:
  # push할 때마다 액션 실행하게 하려면 # 제거
  #push:
  #branches:
  #-develop

  workflow_dispatch: # 수동 실행 설정, 깃허브 액션 페이지에서 클릭으로 실행 가능
    inputs:
      component:
        description: "What component"
        required: true
        default: "web-dev"
      profile:
        description: "What profile"
        required: true
        default: "deploy-dev"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build
        env:
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ secrets.GA_ID }}

      - name: Current timestamp
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')" >> $GITHUB_OUTPUT

      - name: Generate deployment package # (1)
        run: zip ./deploy.zip -r * .[^.]* node_modules

      # --- zip 파일 확인을 위함 ---
      - name: Upload deployment package artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package-${{ steps.timestamp.outputs.date }}
          path: ./deploy.zip
          retention-days: 5

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mobileto-web
          environment_name: Mobileto-web-env-1
          version_label: "${{ steps.timestamp.outputs.date }}"
          region: us-east-1
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300
